var BX={version:"1.0.10.A",encoding:"utf-8",author:"bigtreexu"};
BX.namespace=function(d){if(!d||!d.length){return null}var b=d.split(".");
var c=BX;
for(var a=0;
a!=b.length;
a++){c[b[a]]=c[b[a]]||{};
c=c[b[a]]}};
function $(a){if(!a){return null}else{if(typeof a=="string"){return document.getElementById(a)}else{if(typeof a=="object"){return a}}}}function $A(b){var c=[];
if(b instanceof Array){for(var a=0;
a!=b.length;
a++){c[c.length]=$(b[a])}}else{if(typeof b=="object"&&typeof b.length!="undefined"&&b.length>0){for(var a=0;
a!=b.length;
a++){c[c.length]=$(b[a])}}else{c[0]=$(b)}}return c}function StringBuilder(a){this._buffer=[];
if(a){this.append(a)}}StringBuilder.prototype={append:function(a){this._buffer.push(a)},appendFormat:function(d,b){var c=arguments.length;
if(c<2){return}var e=d;
for(var a=1;
a!=c;
a++){e=e.replace("{"+(a-1)+"}",arguments[a])}this.append(e)},toString:function(){return this._buffer.join("")}};
function Dictionary(){this.buffer=[]}Dictionary.prototype={get:function(a){if(this.contain(a)){return this.buffer[a]}else{return null}},add:function(a,b){if(!this.contain(a)){this.buffer[a]=b}},remove:function(a){if(this.contain(a)){this.buffer[a]=undefined}},getKeys:function(){var b=[];
for(var a in this.buffer){b.push(a)}return b},getValues:function(){var b=[];
for(var a in this.buffer){b.push(this.get(a))}return b},contain:function(a){return(typeof this.buffer[a]!="undefined")}};
BX.namespace("Dom");
BX.namespace("Event");
BX.namespace("Effect");
BX.namespace("Cookie");
BX.Dom={_batch:function(b,c){var d=$A(b);
for(var a=0;
a!=d.length;
a++){if(d[a]){c(d[a])}}},getMouseXY:function(b){var a=_y=0;
a=document.documentElement.scrollLeft;
_y=document.documentElement.scrollTop;
if(b.clientX||b.clientY){a+=b.clientX;
_y+=b.clientY}else{if(b.pageX||b.pageY){a+=b.pageX;
_y+=b.pageY}}return[a,_y]},getXY:function(b){var a=_y=0;
while(b){a+=b.offsetLeft;
_y+=b.offsetTop;
b=b.parentElement}return[a,_y]},getWH:function(a){return[a.offsetWidth,a.offsetHeight]},setOpacity:function(a,c){var b=function(d){d.style.MozOpacity=""+c/100;
d.style.filter="Alpha(Opacity="+c+")"};
this._batch(a,b)},hide:function(a){var b=function(c){c.style.display="none"};
this._batch(a,b)},show:function(a){var b=function(c){c.style.display="block"};
this._batch(a,b)},getClass:function(a){if($(a)){return $(a).className}else{return}},setClass:function(a,c){var b=function(d){d.className=c};
this._batch(a,b)},addClass:function(a,c){if(!c){return}var b=function(e){var f=e.className.split(" ");
for(var d=0;
d!=f.length;
d++){if(f[d]==c){return}}if(e.className.length>0){e.className=e.className+" "+c}else{e.className=c}};
this._batch(a,b)},hasClass:function(c,e){var b=false;
if($(c)){if(!c.className){return}var d=c.className.split(" ");
for(var a=0;
a!=d.length;
a++){if(d[a]==e){b=true;
break}}}return b},removeClass:function(a,c){if(!c){return}var b=function(e){var f=e.className.split(" ");
var g="";
for(var d=0;
d!=f.length;
d++){if(f[d]!=c){g+=f[d]+" "}}if(g==" "){g=""}if(g.length!=0){g=g.substr(0,g.length-1)}e.className=g};
this._batch(a,b)},replaceClass:function(c,b,a){if(!b||!a){return}var d=function(f){var g=f.className.split(" ");
for(var e=0;
e!=g.length;
e++){if(g[e]==b){g[e]=a}}f.className=g.join(" ")};
this._batch(c,d)},setStyle:function(c,b,a){var d=function(e){e.style[b]=a};
this._batch(c,d)},getStyle:function(b,a){return b.style[a]},getElementsByClassName:function(f,e,d){if(!f||!e){return null}var c=cds=[];
cds=$(f).childNodes;
e=e.toUpperCase();
for(var b=0;
b<cds.length;
b++){var a=cds[b].nodeType;
if(a!=3&&a!=8&&cds[b].className.toUpperCase()==e){if(!d||cds[b].nodeName.toUpperCase()==d.toUpperCase()){c[c.length]=cds[b]}}}return c}};
BX.Event={_cache:[],_batch:function(b,c){try{b=$A(b);
for(var a=0;
a<b.length;
a++){c(b[a])}}catch(d){}},addListener:function(c,b,d,a){var e=function(g){var f=g;
var h=function(k){var j=k||window.event;
if(a){d.apply(a,[j,f])}else{d(j,f)}};
if(!BX.Event._cache[g]){BX.Event._cache[g]=[]}if(BX.Event._cache[g][d]){}BX.Event._cache[g][d]=h;
if(g.attachEvent){g.attachEvent("on"+b,h)}else{if(g.addEventListener){g.addEventListener(b,h,false)}else{g["on"+b]=h}}};
this._batch(c,e)},removeListener:function(b,a,c){var d=function(e){if(e.detachEvent){e.detachEvent("on"+a,BX.Event._cache[e][c])}else{if(e.removeEventListener){e.removeEventListener(a,BX.Event._cache[e][c],false)}else{e["on"+a]=null}}BX.Event._cache[e][c]=null};
this._batch(b,d)}};
BX.Effect=function(){};
BX.Effect.prototype={roll:function(g,c,b,f,e){if(!g){return null}if(c<0||b<0){return null}var h=null,d=_t=0,a=null;
if(!f){f=50}if(c<1){c=1}if(c-b<0){a=function(){if(d-b>=0){clearInterval(h);
if(e){e(g)}}else{d=parseInt(d);
_t++;
d=0.5*5*_t*_t;
d=parseInt(d>=b?b:d);
g.style.height=d+"px"}}}else{d=c;
a=function(){if(d-b<=0){clearInterval(h);
if(e){e(g)}}else{d=parseInt(d);
_t++;
d-=0.5*5*_t*_t;
d=parseInt(d<=b?b:d);
g.style.height=d+"px"}}}clearInterval(h);
h=setInterval(a,f)}};
BX.Cookie={getExpDate:function(d,a,c){var b=new Date();
if(typeof d=="number"&&typeof a=="number"&&typeof a=="number"){b.setDate(b.getDate()+parseInt(d));
b.setHours(b.getHours()+parseInt(a));
b.setMinutes(b.getMinutes()+parseInt(c));
return b.toGMTString()}},getCookieVal:function(b){var a=document.cookie.indexOf(";
",b);
if(a==-1){a=document.cookie.length}return unescape(document.cookie.substring(b,a))},getCookie:function(d){var b=d+"=";
var f=b.length;
var a=document.cookie.length;
var e=0;
while(e<a){var c=e+f;
if(document.cookie.substring(e,c)==b){return this.getCookieVal(c)}e=document.cookie.indexOf(" ",e)+1;
if(e==0){break}}return""},getCookies:function(){_Cookie=new Array();
if(document.cookie.indexOf(";
")!=-1){var c,b,d,a,g;
var f=document.cookie.split(";
 ");
var e=f.length;
for(i=0;
i<e;
i++){c=f[i].split("=");
b=c[0];
_value=c[1];
_coo=new Array();
_coo.name=b;
_coo.value=_value;
_Cookie.push(_coo)}}return _Cookie},setCookie:function(b,d,a,f,c,e){document.cookie=b+"="+escape(d)+((a)?";
 expires="+a:"")+((f)?";
 path="+f:"")+((c)?";
 domain="+c:"")+((e)?";
 secure":"")},deleteCookie:function(a,c,b){if(this.getCookie(a)){document.cookie=a+"="+((c)?";
 path="+c:"")+((b)?";
 domain="+b:"")+";
 expires=Thu, 01-Jan-70 00:00:01 GMT"}},clearCookie:function(){cookies=this.getCookies();
for(i=0;
i<cookies.length;
i++){this.deleteCookie(cookies[i]["name"])}},getCookieString:function(){return document.cookie}};
BX.Utility={CACHE_QUERY:null,request:function(a){var b=null;
if(this.CACHE_QUERY==null){this.CACHE_QUERY=this.parseQueryString()}if(this.CACHE_QUERY&&this.CACHE_QUERY[a]){b=decodeURI(this.CACHE_QUERY[a])}return b},parseQueryString:function(){var d=location.search;
if(!d){return null}d=d.substring(1);
var b=d.split("&");
var c=[];
for(i=0;
i<b.length;
i++){var a=b[i].split("=");
if(a.length==2){c[a[0]]=a[1]}}return c}};
BX.isEditMode=function(){var b=0;
var a=location.pathname.toLowerCase();
if(a.indexOf(".aspx")!=-1){b=1}return b}();
var O=BX.Dom;
var V=BX.Event;
var F=BX.Effect;
var C=BX.Cookie;
