package org.teapot.log4j.sql;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

public class DbjStatementWrapper implements Statement {

	private Statement statement;

	public DbjStatementWrapper(Statement statement) {
		System.out.println("" + this.getClass().getName());
		this.statement = statement;
	}

	@Override
	public <T> T unwrap(Class<T> iface) throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return null;
	}

	@Override
	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return false;
	}

	@Override
	public ResultSet executeQuery(String sql) throws SQLException {
		System.out.println("executeQuery sql=" + sql);
		long a = System.currentTimeMillis();
		ResultSet result = this.statement.executeQuery(sql);
		System.out.println("executeQuery " + (System.currentTimeMillis() - a) + "ms");
		return new ResultSetWrapper(result);
	}

	@Override
	public int executeUpdate(String sql) throws SQLException {
		System.out.println("executeUpdate sql=" + sql);
		long a = System.currentTimeMillis();
		int result = this.statement.executeUpdate(sql);
		System.out.println("executeQuery " + (System.currentTimeMillis() - a) + "ms");
		return result;
	}

	@Override
	public void close() throws SQLException {
		this.statement.close();
	}

	@Override
	public int getMaxFieldSize() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return 0;
	}

	@Override
	public void setMaxFieldSize(int max) throws SQLException {
		// TODO 自動生成されたメソッド・スタブ

	}

	@Override
	public int getMaxRows() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return 0;
	}

	@Override
	public void setMaxRows(int max) throws SQLException {
		// TODO 自動生成されたメソッド・スタブ

	}

	@Override
	public void setEscapeProcessing(boolean enable) throws SQLException {
		// TODO 自動生成されたメソッド・スタブ

	}

	@Override
	public int getQueryTimeout() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return 0;
	}

	@Override
	public void setQueryTimeout(int seconds) throws SQLException {
		// TODO 自動生成されたメソッド・スタブ

	}

	@Override
	public void cancel() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ

	}

	@Override
	public SQLWarning getWarnings() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return null;
	}

	@Override
	public void clearWarnings() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ

	}

	@Override
	public void setCursorName(String name) throws SQLException {
		// TODO 自動生成されたメソッド・スタブ

	}

	@Override
	public boolean execute(String sql) throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return false;
	}

	@Override
	public ResultSet getResultSet() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return null;
	}

	@Override
	public int getUpdateCount() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return 0;
	}

	@Override
	public boolean getMoreResults() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return false;
	}

	@Override
	public void setFetchDirection(int direction) throws SQLException {
		// TODO 自動生成されたメソッド・スタブ

	}

	@Override
	public int getFetchDirection() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return 0;
	}

	@Override
	public void setFetchSize(int rows) throws SQLException {
		// TODO 自動生成されたメソッド・スタブ

	}

	@Override
	public int getFetchSize() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return 0;
	}

	@Override
	public int getResultSetConcurrency() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return 0;
	}

	@Override
	public int getResultSetType() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return 0;
	}

	@Override
	public void addBatch(String sql) throws SQLException {
		// TODO 自動生成されたメソッド・スタブ

	}

	@Override
	public void clearBatch() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ

	}

	@Override
	public int[] executeBatch() throws SQLException {
		return this.statement.executeBatch();
	}

	@Override
	public Connection getConnection() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return null;
	}

	@Override
	public boolean getMoreResults(int current) throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return false;
	}

	@Override
	public ResultSet getGeneratedKeys() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return null;
	}

	@Override
	public int executeUpdate(String sql, int autoGeneratedKeys)
			throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return 0;
	}

	@Override
	public int executeUpdate(String sql, int[] columnIndexes)
			throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return 0;
	}

	@Override
	public int executeUpdate(String sql, String[] columnNames)
			throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return 0;
	}

	@Override
	public boolean execute(String sql, int autoGeneratedKeys)
			throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return false;
	}

	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return false;
	}

	@Override
	public boolean execute(String sql, String[] columnNames)
			throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return false;
	}

	@Override
	public int getResultSetHoldability() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return 0;
	}

	@Override
	public boolean isClosed() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return false;
	}

	@Override
	public void setPoolable(boolean poolable) throws SQLException {
		// TODO 自動生成されたメソッド・スタブ

	}

	@Override
	public boolean isPoolable() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return false;
	}

	@Override
	public void closeOnCompletion() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ

	}

	@Override
	public boolean isCloseOnCompletion() throws SQLException {
		// TODO 自動生成されたメソッド・スタブ
		return false;
	}

}
